# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wayne.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ValveLayout_0 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ValveLayout_0.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_0.setObjectName("ValveLayout_0")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(1)
        self.spinBox.setObjectName("spinBox")
        self.ValveLayout_0.addWidget(self.spinBox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ValveLayout_0.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 10, 71, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ValveLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ValveLayout_1.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_1.setObjectName("ValveLayout_1")
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setMaximum(1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.ValveLayout_1.addWidget(self.spinBox_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ValveLayout_1.addWidget(self.label_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(170, 10, 71, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.ValveLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.ValveLayout_2.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_2.setObjectName("ValveLayout_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setMaximum(1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.ValveLayout_2.addWidget(self.spinBox_3)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.ValveLayout_2.addWidget(self.label_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(250, 10, 71, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.ValveLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.ValveLayout_3.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_3.setObjectName("ValveLayout_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setMaximum(1)
        self.spinBox_4.setObjectName("spinBox_4")
        self.ValveLayout_3.addWidget(self.spinBox_4)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.ValveLayout_3.addWidget(self.label_4)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(330, 10, 71, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.ValveLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.ValveLayout_4.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_4.setObjectName("ValveLayout_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setMaximum(1)
        self.spinBox_5.setObjectName("spinBox_5")
        self.ValveLayout_4.addWidget(self.spinBox_5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.ValveLayout_4.addWidget(self.label_5)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(410, 10, 71, 71))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.ValveLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.ValveLayout_5.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_5.setObjectName("ValveLayout_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.spinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_6.setMaximum(1)
        self.spinBox_6.setObjectName("spinBox_6")
        self.ValveLayout_5.addWidget(self.spinBox_6)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.ValveLayout_5.addWidget(self.label_6)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(490, 10, 71, 71))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.ValveLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.ValveLayout_6.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_6.setObjectName("ValveLayout_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.spinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_7.setMaximum(1)
        self.spinBox_7.setObjectName("spinBox_7")
        self.ValveLayout_6.addWidget(self.spinBox_7)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.ValveLayout_6.addWidget(self.label_7)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(570, 10, 71, 71))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.ValveLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.ValveLayout_7.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_7.setObjectName("ValveLayout_7")
        self.spinBox_8 = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.spinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_8.setMaximum(1)
        self.spinBox_8.setObjectName("spinBox_8")
        self.ValveLayout_7.addWidget(self.spinBox_8)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.ValveLayout_7.addWidget(self.label_8)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 100, 71, 71))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.ValveLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.ValveLayout_8.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_8.setObjectName("ValveLayout_8")
        self.spinBox_9 = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.spinBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_9.setMaximum(1)
        self.spinBox_9.setObjectName("spinBox_9")
        self.ValveLayout_8.addWidget(self.spinBox_9)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.ValveLayout_8.addWidget(self.label_9)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(90, 100, 71, 71))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.ValveLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.ValveLayout_9.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_9.setObjectName("ValveLayout_9")
        self.spinBox_10 = QtWidgets.QSpinBox(self.verticalLayoutWidget_10)
        self.spinBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_10.setMaximum(1)
        self.spinBox_10.setObjectName("spinBox_10")
        self.ValveLayout_9.addWidget(self.spinBox_10)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.ValveLayout_9.addWidget(self.label_10)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(170, 100, 71, 71))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.ValveLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.ValveLayout_10.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_10.setObjectName("ValveLayout_10")
        self.spinBox_11 = QtWidgets.QSpinBox(self.verticalLayoutWidget_11)
        self.spinBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_11.setMaximum(1)
        self.spinBox_11.setObjectName("spinBox_11")
        self.ValveLayout_10.addWidget(self.spinBox_11)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.ValveLayout_10.addWidget(self.label_11)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(250, 100, 71, 71))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.ValveLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.ValveLayout_11.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_11.setObjectName("ValveLayout_11")
        self.spinBox_12 = QtWidgets.QSpinBox(self.verticalLayoutWidget_12)
        self.spinBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_12.setMaximum(1)
        self.spinBox_12.setObjectName("spinBox_12")
        self.ValveLayout_11.addWidget(self.spinBox_12)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.ValveLayout_11.addWidget(self.label_12)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(330, 100, 71, 71))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.ValveLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.ValveLayout_12.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_12.setObjectName("ValveLayout_12")
        self.spinBox_13 = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.spinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_13.setMaximum(1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.ValveLayout_12.addWidget(self.spinBox_13)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.ValveLayout_12.addWidget(self.label_13)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(410, 100, 71, 71))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.ValveLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.ValveLayout_13.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_13.setObjectName("ValveLayout_13")
        self.spinBox_14 = QtWidgets.QSpinBox(self.verticalLayoutWidget_14)
        self.spinBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_14.setMaximum(1)
        self.spinBox_14.setObjectName("spinBox_14")
        self.ValveLayout_13.addWidget(self.spinBox_14)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.ValveLayout_13.addWidget(self.label_14)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(490, 100, 71, 71))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.ValveLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.ValveLayout_14.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_14.setObjectName("ValveLayout_14")
        self.spinBox_15 = QtWidgets.QSpinBox(self.verticalLayoutWidget_15)
        self.spinBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_15.setMaximum(1)
        self.spinBox_15.setObjectName("spinBox_15")
        self.ValveLayout_14.addWidget(self.spinBox_15)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.ValveLayout_14.addWidget(self.label_15)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(570, 100, 71, 71))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.ValveLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.ValveLayout_15.setContentsMargins(0, 0, 0, 0)
        self.ValveLayout_15.setObjectName("ValveLayout_15")
        self.spinBox_16 = QtWidgets.QSpinBox(self.verticalLayoutWidget_16)
        self.spinBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_16.setMaximum(1)
        self.spinBox_16.setObjectName("spinBox_16")
        self.ValveLayout_15.addWidget(self.spinBox_16)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.ValveLayout_15.addWidget(self.label_16)
        self.deflateButton = QtWidgets.QPushButton(self.centralwidget)
        self.deflateButton.setGeometry(QtCore.QRect(170, 220, 111, 51))
        self.deflateButton.setObjectName("deflateButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(370, 220, 111, 51))
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wayne Control SUPER MEGA GIGA"))
        self.label.setText(_translate("MainWindow", "Valve 0"))
        self.label_2.setText(_translate("MainWindow", "Valve 1"))
        self.label_3.setText(_translate("MainWindow", "Valve 2"))
        self.label_4.setText(_translate("MainWindow", "Valve 3"))
        self.label_5.setText(_translate("MainWindow", "Valve 4"))
        self.label_6.setText(_translate("MainWindow", "Valve 5"))
        self.label_7.setText(_translate("MainWindow", "Valve 6"))
        self.label_8.setText(_translate("MainWindow", "Valve 7"))
        self.label_9.setText(_translate("MainWindow", "Valve 8"))
        self.label_10.setText(_translate("MainWindow", "Valve 9"))
        self.label_11.setText(_translate("MainWindow", "Valve 10"))
        self.label_12.setText(_translate("MainWindow", "Valve 11"))
        self.label_13.setText(_translate("MainWindow", "Valve 12"))
        self.label_14.setText(_translate("MainWindow", "Valve 13"))
        self.label_15.setText(_translate("MainWindow", "Valve 14"))
        self.label_16.setText(_translate("MainWindow", "Valve 15"))
        self.deflateButton.setText(_translate("MainWindow", "Deflate"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
